backend:
  name: github
  repo: bycoast/nampula-e-a-cena
  branch: main
  base_url: https://netlify-cms-github-oauth-provider-qlyb.onrender.com
  auth_endpoint: /auth

locale: pt
media_folder: "imagens"
public_folder: "/imagens"

collections:
  - name: "noticias"
    label: "Notícias"
    folder: "_noticias"
    create: true
    fields:
      - {label: "Título", name: "titulo", widget: "string"}
      - {label: "Data", name: "data", widget: "datetime", format: "DD/MM/YYYY", date_format: "DD/MM/YYYY", time_format: false}
      - {label: "Categoria", name: "categoria", widget: "select", options: ["Política", "Economia", "Saúde", "Educação", "Tecnologia", "Segurança", "Sociedade", "Ambiente", "Internacional", "Cultura"]}
      - {label: "Descrição", name: "desc", widget: "text"}
      - {label: "Imagem URL", name: "img", widget: "string", required: false}
      - {label: "Link fonte", name: "link_real", widget: "string", required: false}
      - {label: "Tipo", name: "tipo", widget: "hidden", default: "noticia"}
