backend:
  name: github
  repo: ByCoast/nampula-e-a-cena
  branch: main

media_folder: "images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "dados"
    label: "Dados"
    files:
      - name: "noticias"
        label: "Notícias e Vagas"
        file: "dados.json"
        fields:
          - { label: "Conteúdo", name: "body", widget: "json" }
